name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: Node.js version to use
    default: 22.x
    required: true
  working-directory:
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Set up Node.js version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/node-modules
        key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-directory, 'package-lock.json')) }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: ${{ inputs.target-env != 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
