name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: |
          exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will be printing if the previous step has succeeded"
      - name: I will execute
        if: ${{ failure() }}
        run: |
          echo "I will be printing if the previous step has failed"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: |
          echo "I will always be printing except when the workflow has been cancelled"
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: |
          echo "I will be printing if the workflow has been cancelled"
