name: 17 - Custom Actions - JS
run-name: "17: 02 - Custom Actions - JS"

on:
  workflow_dispatch: 

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update