name: "17 - 03: Custom Actions - Docker"

on:
  workflow_dispatch: 
    inputs:
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://www.invalid-githubbubububub.com'
          - 'invalid-url'
      max_attempts: 
        description: The maximum number of attempts to ping the URL until the action fails
        default: '10'
        required: false
      delay:
        description: The delay in seconds between attempts
        default: '5'
        required: false
  
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_attempts: ${{ inputs.max_attempts }}
          delay: ${{ inputs.delay }}