name: "18 - 02: Reusable Workflows"

on:
  workflow_dispatch:
    
jobs:
  deploy:
    uses: ./.github/workflows/18-01-reusable-workflow.yaml
    with:
      target-directory: dummy-directory
  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs from deploy job
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"