name: "18 - 03: Reusable Workflows"

on:
  workflow_dispatch:
    
jobs:
  deploy:
    uses: ./.github/workflows/18-01-reusable-workflow.yaml
    with:
      target-directory: dummy-directory
  e2e-tests:
    uses: maor-klir/github-actions-course-e2e/.github/workflows/e2e.yaml@main
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}