name: "18 - 03: Reusable Workflows"

on:
  workflow_dispatch:
    
jobs:
  deploy:
    uses: ./.github/workflows/18-01-reusable-workflow.yaml
    with:
      target-directory: dummy-directory
  e2e-tests:
    uses: maor-klir/github-actions-course-e2e/.github/workflows/e2e.yaml@main

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs from deploy job
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"